# Generated by Django 4.2.7 on 2023-11-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocatorapp', '0002_alter_system_actualdateofreturn_alter_system_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='ActualDateofReturn',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='Amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='DateofPurchase',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='DateofReturn',
            field=models.DateField(blank=True, null=True),
        ),
    ]
