# Generated by Django 4.2.7 on 2023-11-27 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('allocatorapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('isactive', models.BooleanField(default=True, verbose_name='active')),
                ('Name', models.CharField(max_length=50)),
                ('Mobile', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Have_Own_System', models.BooleanField(default=False)),
                ('Batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocatorapp.batch')),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='SystemAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('From', models.TimeField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('To', models.TimeField(null=True)),
                ('Batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='allocatorapp.batch')),
                ('students', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='Batch', chained_model_field='Batch', limit_choices_to={'Have_Own_System': False, 'systemallocation__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student')),
                ('system', models.ForeignKey(limit_choices_to={'systemallocation__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='allocatorapp.system')),
            ],
        ),
    ]
